### ISSUE TITLE
"Assign Colors" based on auxiliary data not fully working

### ISSUE THREAD

**Issue by sabrinadiemert** [bfrgoncalves/Online-PhyloViZ#29]
For some reason, when I select "Assign Colors" based on my auxiliary data (Source), only one of the two sources shows coloured appropriately on my plot - the other category remains grey. Is this a bug, or is there something awry with my data set? 

[Link to my tree.](https://online.phyloviz.net/main/dataset/share/cff51111a3ca3ad6cf9c1394436ce716fc5ff8c7cc5aeb3988035190d4184442fd24f5264ef2add20e3c2db4e0975181e33b595ea835c62f6984ecb26f4e746b8a2cee5882f1a650586967be014443503faa81468bd5bfbacf0a145ab41456a9)

**Comment by bfrgoncalves** [comment]
Hi @sabrinadiemert!

We are currently working on this problem in the next version of PHYLOViZ Online but the current version of PHYOViZ is not supporting dots as part of the identifiers since they are special characters when trying to perform associations between the profile identifiers and the metadata. As so, I suggest trying to replace the IDs in the profiles and in the metadata like "GCA_000486205.1" to "GCA_000486205-1", and then upload again the data with those modifications.

If the error persists, please contact me again.

**Comment by sabrinadiemert** [comment]
Thanks @bfrgoncalves - that fixed the problem. I didn't realize that the naming of the IDs would affect the other metadata for those entries. Cheers!
